### ISSUE TITLE
Connect to a machine with username and no password.

### ISSUE THREAD

**Issue by ilija-lazoroski** [jborean93/pypsrp#119]
I have a machine on which I have enabled winrm, created an account that has no password and allowed blank passwords for remote connections. On other hand I have linux and windows machine on which I have followed the installation for `pypsrp`.

I want to connect via `pypsrp` to an account without password. The machine is going to be used just for testing purposes.

If I try to connect to the machine manually using `Enter-PSSession` I can connect with a blank password
![image](https://user-images.githubusercontent.com/15820737/130458139-fd0ad5d9-af85-4fe1-881c-b3701e884266.png)

If I try to connect to the same machine using `pypsrp` client and the same options:

On linux I am getting

```Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/spnego/gss.py", line 365, in __init__
    context_req=context_req)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/spnego/gss.py", line 217, in _get_gssapi_credential
    cred = gssapi.Credentials(name=username, usage=usage, mechs=[mech])
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gssapi/creds.py", line 64, in __new__
    store=store)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gssapi/creds.py", line 137, in acquire
    mechs, usage)
  File "gssapi/raw/creds.pyx", line 161, in gssapi.raw.creds.acquire_cred
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100001): SPNEGO cannot find mechanisms to negotiate

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "connect_winrm.py", line 27, in <module>
    print(client.execute_cmd("dir"))
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pypsrp/client.py", line 159, in execute_cmd
    with WinRS(self.wsman, environment=environment) as shell:
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pypsrp/shell.py", line 98, in __enter__
    self.open()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pypsrp/shell.py", line 204, in open
    option_set=options)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pypsrp/wsman.py", line 270, in create
    option_set, selector_set, timeout)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pypsrp/wsman.py", line 389, in invoke
    response = self.transport.send(xml)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pypsrp/wsman.py", line 761, in send
    return self._send_request(prep_request)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pypsrp/wsman.py", line 765, in _send_request
    self.connection_timeout, self.read_timeout
  File "/home/ubuntu/.local/lib/python3.7/site-packages/requests/sessions.py", line 662, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pypsrp/negotiate.py", line 88, in response_hook
    response = self.handle_401(response, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pypsrp/negotiate.py", line 121, in handle_401
    options=spnego_options)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/spnego/auth.py", line 96, in client
    'initiate')
  File "/home/ubuntu/.local/lib/python3.7/site-packages/spnego/auth.py", line 73, in _new_context
    return proxy(username, password, hostname, service, channel_bindings, context_req, usage, proto, options)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/spnego/gss.py", line 367, in __init__
    reraise(SpnegoError(base_error=gss_err, context_msg="Getting GSSAPI credential"))
  File "/home/ubuntu/.local/lib/python3.7/site-packages/spnego/_compat.py", line 60, in reraise
    raise exc
spnego.exceptions.SpnegoError: SpnegoError (4294967295): Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100001): SPNEGO cannot find mechanisms to negotiate, Context: Getting GSSAPI credential
```

And on windows I am getting:
```Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Python37\lib\site-packages\urllib3\connection.py", line 360, in connect
    ssl_context=context,
  File "C:\Python37\lib\site-packages\urllib3\util\ssl_.py", line 383, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "C:\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Python37\lib\ssl.py", line 859, in _create
    self.do_handshake()
  File "C:\Python37\lib\ssl.py", line 1128, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Python37\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.1.9', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\winrm-client.py", line 30, in <module>
    print(client.execute_cmd("dir"))
  File "C:\Python37\lib\site-packages\pypsrp\client.py", line 159, in execute_cmd
    with WinRS(self.wsman, environment=environment) as shell:
  File "C:\Python37\lib\site-packages\pypsrp\shell.py", line 98, in __enter__
    self.open()
  File "C:\Python37\lib\site-packages\pypsrp\shell.py", line 204, in open
    option_set=options)
  File "C:\Python37\lib\site-packages\pypsrp\wsman.py", line 270, in create
    option_set, selector_set, timeout)
  File "C:\Python37\lib\site-packages\pypsrp\wsman.py", line 389, in invoke
    response = self.transport.send(xml)
  File "C:\Python37\lib\site-packages\pypsrp\wsman.py", line 761, in send
    return self._send_request(prep_request)
  File "C:\Python37\lib\site-packages\pypsrp\wsman.py", line 765, in _send_request
    self.connection_timeout, self.read_timeout
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python37\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.1.9', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
```

For both linux and windows if I specify `ssl=True, auth='basic', encryption='never'` and blank password then I can connect to the machine.

I would really appreciate if you can point out what am I doing wrong...

**Comment by jborean93** [comment]
Using a password that is blank is not the same as not providing a password in pypsrp. By doing `password=None` you are telling the underlying auth provider to get the password from a credential cache (the cache behaviour differs across platforms). I would try doing `password=""` to explicitly give a password that is blank/empty but I'm unsure if this actually works or not.

> spnego.exceptions.SpnegoError: SpnegoError (4294967295): Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100001): SPNEGO cannot find mechanisms to negotiate, Context: Getting GSSAPI credential

This error indicates it's trying to use GSSAPI to authenticate the user and it's not liking the unset password. When you don't specify a password for negotiate/ntlm/kerberos auth then it's going to try to get the credential in an existing cache and error when there is none. If the password is blank/unset then doing `password=""` might work but is totally untested and I wouldn't be surprised if it fails in some other way. You could combine that with `auth="ntlm"` to skip Kerberos entirely but once again I'm unsure if it will actually work.

> requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.1.9', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

Windows is the same but omitting the password will mean it's using your current user's security context and unlike Linux this is pretty much guaranteed to be present. So it's able to get a credential, which may not be the one you are looking for, but now it's failing to validate the SSL cert of the endpoint. This is most likely because you are connecting with an IP whereas certs typically are registered to a hostname. If you wish to ignore any cert validation you can set `cert_validation=False`.

> For both linux and windows if I specify ssl=True, auth='basic', encryption='never' and blank password then I can connect to the machine.

Basic auth is completely different from negotiate/ntlm/kerberos and will just send the base64 encoded header of `username:` so that would be why it works. I'm unsure why that isn't failing with the cert validation issue on Windows as cert validation doesn't apply to authentication.

Ultimately I would highly recommend you set a password for that account and authenticate with that password. Having network access without a password set is a very dangerous scenario, especially considering PSRemoting is usually done with admin accounts. If you need some sort of easy logon for a kiosk like account then consider [Automatic Logon](https://docs.microsoft.com/en-us/troubleshoot/windows-server/user-profiles-and-logon/turn-on-automatic-logon) for automatically logging on an account with a password for the interactive scenario.
