### ISSUE TITLE
urllib3.exceptions.HeaderParsingError when copy file from local machine

### ISSUE THREAD

**Issue by w93163red** [jborean93/pypsrp#39]
Hi,

When I tried to copy the local file to the remote machine, I encountered this problem:
```
2019-06-25 15:22:09,491 - Failed to parse headers (url=http://x.x.x.x:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 399, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\response.py", line 72, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2019-06-25 15:22:29,498 - Failed to parse headers (url=http://x.x.x.x:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 399, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\response.py", line 72, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2019-06-25 15:22:49,504 - Failed to parse headers (url=http://x.x.x.x:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 399, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\response.py", line 72, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2019-06-25 15:23:09,513 - Failed to parse headers (url=http://x.x.x.x:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 399, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\response.py", line 72, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2019-06-25 15:23:29,521 - Failed to parse headers (url=http://x.x.x.x:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 399, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\response.py", line 72, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2019-06-25 15:23:45,852 - Failed to parse headers (url=http://x.x.x.x:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 399, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\response.py", line 72, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2019-06-25 15:23:45,853 - Closing Runspace Pool
2019-06-25 15:23:45,868 - Failed to parse headers (url=http://x.x.x.x:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 399, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "C:\Users\wlingxiang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\response.py", line 72, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
```
The code I used is listed below:
```python
    machine_IP = ""
    username = ""
    # password = getpass.getpass(prompt="Password: ")
    password = ""
    client = Client(machine_IP, username=username, password=password, ssl=False)
    print("Create directories on remote machine")
    client.execute_ps("New-Item -Path c:/Temp/Scripts/ -ItemType Directory")
    client.execute_ps("New-Item -Path c:/Temp/response_file/ -ItemType Directory")
    for filename in os.listdir(SCRIPT_DIR):
        client.copy(SCRIPT_DIR + filename, REMOTE_SCRIPT_DIR + filename)

    for filename in os.listdir(RESPONSE_DIR):
        client.copy(RESPONSE_DIR + filename, REMOTE_RESPONSE_FILE_DIR + filename)
```

May I know how to resolve this question? Thanks!

**Comment by jborean93** [comment]
Interesting I've never seen this issue before. Are you finding it's just the copy functions that are problematic or are you also seeing it with `execute_ps`? Are you able to capture the traffic with Wireshark and share that info?

**Comment by w93163red** [comment]
The file can still be copied to the remote machine, it just popped out this error msg. 
For capture the traffic, I didn't find anything useful.
[traffic.log](https://github.com/jborean93/pypsrp/files/3378224/traffic.log)

**Comment by jborean93** [comment]
The message seem fine, potentially something about the `--Encrypted Boundary` is causing some issues with urllib3 parsing the response but considering the code is not actually erroring out and the file is being copied across we might be able to safely ignore it. Some info is mentioned at https://github.com/urllib3/urllib3/issues/800 and a possible solution is to just filter out this "warning" like https://github.com/home-assistant/home-assistant/pull/17042. I would need to investigate it a bit further as it could still be something I need to do a bit better.

Are you able to;

* Confirm that while you see the warnings the actual script doesn't error out and the file is copied?
* The output of `pip list` on your host, I'm mostly curious to see the `reqests` and `urllib3` versions that you have.

**Comment by w93163red** [comment]
Hi Jordan,
I think the file is actually copied and the functionality is working fine. I use the pypsrp part of my automation script, so I used it every day and do not see any errors. 
The pip list is attached:
```
Package            Version
------------------ -----------
asn1crypto         0.24.0
astroid            2.2.5
attrs              19.1.0
backcall           0.1.0
bcrypt             3.1.7
bleach             3.1.0
certifi            2019.6.16
cffi               1.12.3
chardet            3.0.4
colorama           0.4.1
cryptography       2.7
decorator          4.4.0
defusedxml         0.6.0
entrypoints        0.3
idna               2.8
ipykernel          5.1.1
ipython            7.6.0
ipython-genutils   0.2.0
ipywidgets         7.5.0
isort              4.3.21
jedi               0.14.0
Jinja2             2.10.1
jsonschema         3.0.1
jupyter            1.0.0
jupyter-client     5.2.4
jupyter-console    6.0.0
jupyter-core       4.5.0
lazy-object-proxy  1.4.1
MarkupSafe         1.1.1
mccabe             0.6.1
mistune            0.8.4
mysql-connector    2.2.9
mysqlclient        1.4.2.post1
nbconvert          5.5.0
nbformat           4.4.0
notebook           5.7.8
ntlm-auth          1.3.0
pandocfilters      1.4.2
paramiko           2.6.0
parso              0.5.0
pi                 0.1.2
pickleshare        0.7.5
pip                19.1.1
prometheus-client  0.7.1
prompt-toolkit     2.0.9
psutil             5.6.3
pycparser          2.19
Pygments           2.4.2
pylint             2.3.1
PyNaCl             1.3.0
pypsrp             0.3.1
pyrsistent         0.15.2
python-dateutil    2.8.0
pywinpty           0.5.5
PyYAML             5.1.1
pyzmq              18.0.2
qtconsole          4.5.1
redis              3.2.1
requests           2.22.0
Send2Trash         1.5.0
setuptools         40.8.0
six                1.12.0
terminado          0.8.2
testpath           0.4.2
tornado            6.0.3
traitlets          4.3.2
typed-ast          1.4.0
urllib3            1.25.3
wcwidth            0.1.7
webencodings       0.5.1
wget               3.2
widgetsnbextension 3.5.0
wrapt              1.11.2
```
