### ISSUE TITLE
Connect windows server 2008 r2 fail

### ISSUE THREAD

**Issue by AndrewTsao** [jborean93/pypsrp#54]
I add ```credssp_disable_tlsv1_2=True``` to WSMan option, still fail.

```python
import logging as log
from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan

def test_psrp():
    # creates a https connection with explicit kerberos auth and implicit credentials
    wsman = WSMan("windows server 2008 r2",
                  port=5985,
                  auth="credssp",
                  username="user",
                  password="xxx",
                  credssp_disable_tlsv1_2=True,
                  ssl=False)

    with RunspacePool(wsman) as pool:
        # execute 'Get-Process | Select-Object Name'
        ps = PowerShell(pool)
        ps.add_script(r'Start-Job -ScriptBlock { Python.exe  }')
        #ps.add_cmdlet("Get-Process")
        ps.add_cmdlet("Out-String").add_parameter("Stream")
        output = ps.invoke()
        if ps.had_errors:
            log.error(str(ps.streams.error[0]))
        print('\n'.join(output))


if __name__ == "__main__":
    test_psrp()
```
Get this exception.

```
Traceback (most recent call last):
  File "c:\Users\xxxx\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\xxxx\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\xxxx\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\Projects\test\credssp\test.py", line 62, in <module>
    test_psrp()
  File "e:\Projects\test\credssp\test.py", line 49, in test_psrp
    with RunspacePool(wsman) as pool:
  File "e:\Projects\test\credssp\.venv\lib\site-packages\pypsrp\powershell.py", line 198, in __enter__
    self.open()
  File "e:\Projects\test\credssp\.venv\lib\site-packages\pypsrp\powershell.py", line 506, in open
    self.shell.open(options, open_content)
  File "e:\Projects\test\credssp\.venv\lib\site-packages\pypsrp\shell.py", line 204, in open
    option_set=options)
  File "e:\Projects\test\credssp\.venv\lib\site-packages\pypsrp\wsman.py", line 259, in create
    option_set, selector_set, timeout)
  File "e:\Projects\test\credssp\.venv\lib\site-packages\pypsrp\wsman.py", line 378, in invoke
    response = self.transport.send(xml)
  File "e:\Projects\test\credssp\.venv\lib\site-packages\pypsrp\wsman.py", line 735, in send
    return self._send_request(prep_request, hostname)
  File "e:\Projects\test\credssp\.venv\lib\site-packages\pypsrp\wsman.py", line 739, in _send_request
    self.connection_timeout, self.read_timeout
  File "e:\Projects\test\credssp\.venv\lib\site-packages\requests\sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "e:\Projects\test\credssp\.venv\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "e:\Projects\test\credssp\.venv\lib\site-packages\requests_credssp\credssp.py", line 448, in response_hook
    response = self.handle_401(response, **kwargs)
  File "e:\Projects\test\credssp\.venv\lib\site-packages\requests_credssp\credssp.py", line 484, in handle_401
    step_name)
  File "e:\Projects\test\credssp\.venv\lib\site-packages\requests_credssp\credssp.py", line 517, in _get_credssp_token
    raise AuthenticationException(error_msg)
requests_credssp.exceptions.AuthenticationException: Server did not response with a CredSSP token after step Step 5. Delegate Credentials - actual ''
```

**Comment by jborean93** [comment]
You shouldn't have to set `credssp_disable_tlsv1_2=True` for any hosts as there is a KB available for Server 2008 R2, it's only there if you really really need it and cannot install the fix and enable that setting from Microsoft. In saying that the error you receive is happening right at the end of the CredSSP authentication process, after the credentials are initially validated. I'm unsure why it is erroring out like this but you will have to potentially look into the Windows Security event log to figure out why it might be happening.

**Comment by AndrewTsao** [comment]
This problem was solved by enabling TLS1.2. reference [TLS 1.2 Support](https://docs.ansible.com/ansible/latest/os_guide/windows_winrm.html#id14)[](https://docs.ansible.com/ansible/latest/os_guide/windows_winrm.html#tls-1-2-support)
```
Function Enable-TLS12 {
    param(
        [ValidateSet("Server", "Client")]
        [String]$Component = "Server"
    )

    $protocols_path = 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols'
    New-Item -Path "$protocols_path\TLS 1.2\$Component" -Force
    New-ItemProperty -Path "$protocols_path\TLS 1.2\$Component" -Name Enabled -Value 1 -Type DWORD -Force
    New-ItemProperty -Path "$protocols_path\TLS 1.2\$Component" -Name DisabledByDefault -Value 0 -Type DWORD -Force
}

Enable-TLS12 -Component Server

# Not required but highly recommended to enable the Client side TLS 1.2 components
Enable-TLS12 -Component Client

Restart-Computer
```
