### ISSUE TITLE
Invoke Exchange server cmdlet returns 404 html

### ISSUE THREAD

**Issue by NotSoWell** [jborean93/pypsrp#66]
Hi! I'm trying to implement following PS code with pypsrp for the Exchange server:
```powershell
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://srv-exch01-dca/PowerShell/ -Authentication Kerberos -Credential $UserCredential
Import-PSSession $Session
foreach ($server in Get-ExchangeServer) { Get-MessageTrackingLog -Server "$server" -Start '03-15-2020' -End '03-19-2020' -ResultSize UNLIMITED}
```

The PS code above works pretty well, but i got errors when i start my python script:
```python
from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan

wsman = WSMan(server="srv-exch01-dca", path="PowerShell", username="USER", password="PASSWORD", auth="kerberos", ssl=False, cert_validation=False)

with RunspacePool(wsman, configuration_name="Microsoft.Exchange") as pool:
    ps = PowerShell(pool)
    ps.add_script('foreach ($server in Get-ExchangeServer) { Get-MessageTrackingLog -Server "$server" -Start "3-15-2020" -End "03-19-2020" -ResultSize UNLIMITED}')
    output = ps.invoke()
    print(output)
```

I turned on logging and get this output with exception:
```
2020-03-20 14:48:34,705 - pypsrp.wsman - DEBUG - Initialising WSMan class with maximum envelope size of 153600 and operation timeout of 20
2020-03-20 14:48:34,705 - pypsrp.wsman - DEBUG - Initialising HTTP transport for endpoint: http://srv-exch01-dca.dixy.local:5985/PowerShell, auth: USER, user: kerberos
2020-03-20 14:48:34,706 - pypsrp.wsman - DEBUG - Creating WSMan header (Action: http://schemas.microsoft.com/wbem/wsman/1/windows/shell/Send, Resource URI: http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd, Option Set: None, Selector Set: {'ShellId': '00000000-0000-0000-0000-000000000000'}
2020-03-20 14:48:34,706 - pypsrp.powershell - INFO - Initialising RunspacePool object for configuration Microsoft.Exchange
2020-03-20 14:48:34,707 - pypsrp.powershell - INFO - Openning a new Runspace Pool on remote host
2020-03-20 14:48:34,708 - pypsrp.messages - DEBUG - Packing PSRP message: <Obj RefId="0"><MS><Version N="protocolversion">2.3</Version><Version N="PSVersion">2.0</Version><Version N="SerializationVersion">1.1.0.1</Version></MS></Obj>
2020-03-20 14:48:34,709 - pypsrp.messages - DEBUG - Packing PSRP message: <Obj RefId="0"><MS><I32 N="MinRunspaces">1</I32><I32 N="MaxRunspaces">1</I32><Obj N="PSThreadOptions" RefId="1"><TN RefId="0"><T>System.Management.Automation.Runspaces.PSThreadOptions</T><T>System.Enum</T><T>System.ValueType</T><T>System.Object</T></TN><ToString>Default</ToString><I32>0</I32></Obj><Obj N="ApartmentState" RefId="2"><TN RefId="1"><T>System.Management.Automation.Runspaces.ApartmentState</T><T>System.Enum</T><T>System.ValueType</T><T>System.Object</T></TN><ToString>UNKNOWN</ToString><I32>2</I32></Obj><Obj N="HostInfo" RefId="3"><MS><B N="_isHostNull">true</B><B N="_isHostUINull">true</B><B N="_isHostRawUINull">true</B><B N="_useRunspaceHost">true</B></MS></Obj><Nil N="ApplicationArguments" /></MS></Obj>
2020-03-20 14:48:34,709 - pypsrp.wsman - DEBUG - Creating WSMan header (Action: http://schemas.xmlsoap.org/ws/2004/09/transfer/Create, Resource URI: http://schemas.microsoft.com/powershell/Microsoft.Exchange, Option Set: {'protocolversion': '2.3'}, Selector Set: None
2020-03-20 14:48:34,710 - pypsrp.wsman - DEBUG - Building requests session with auth kerberos
2020-03-20 14:48:34,711 - pypsrp.encryption - DEBUG - Initialising WinRMEncryption helper for protocol application/HTTP-SPNEGO-session-encrypted
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 382, in invoke
    raise self._parse_wsman_fault(err.response_text)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 515, in _parse_wsman_fault
    xml = ET.fromstring(xml_text)
  File "C:\Python\lib\xml\etree\ElementTree.py", line 1314, in XML
2020-03-20 14:48:34,733 - pypsrp.wsman - DEBUG - Received message: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>

2020-03-20 14:48:34,733 - pypsrp.wsman - ERROR - Failed to parse WSManFault message on WinRM error response, raising original WinRMTransportError
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 49

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    with RunspacePool(wsman, configuration_name="Microsoft.Exchange") as pool:
  File "C:\Python\lib\site-packages\pypsrp\powershell.py", line 200, in __enter__
    self.open()
  File "C:\Python\lib\site-packages\pypsrp\powershell.py", line 508, in open
    self.shell.open(options, open_content)
  File "C:\Python\lib\site-packages\pypsrp\shell.py", line 204, in open
    option_set=options)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 259, in create
    option_set, selector_set, timeout)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 387, in invoke
    raise err
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 378, in invoke
    response = self.transport.send(xml)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 711, in send
    self._send_request(prep_request, hostname)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 765, in _send_request
    raise WinRMTransportError('http', code, response_text)
pypsrp.exceptions.WinRMTransportError: Bad HTTP response returned from the server. Code: 404, Content: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>
'

Process finished with exit code 1
```

I will be glad if someone can help me

**Comment by NotSoWell** [comment]
After some research i find out that actual port is 80.
This cmdlet is working in PS:
```PowerShell
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://srv-exch01-dca:80
/PowerShell/ -Authentication Kerberos -Credential $UserCredential
```

But my code still throw exception.
Code:
```python
from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan

wsman = WSMan(
    server=r"srv-exch01-dca",
    auth="kerberos",
    ssl=False,
    cert_validation=False,
    username="USER",
    password="PASSWORD",
    path='PowerShell',
    port=80
)

with RunspacePool(wsman, configuration_name="Microsoft.Exchange") as pool:
    ps = PowerShell(pool)
    ps.add_script('foreach ($server in Get-ExchangeServer) { Get-MessageTrackingLog -Server "$server" -Start "3-15-2020" -End "03-19-2020" -ResultSize UNLIMITED}')
    output = ps.invoke()
    print(output)
```

Exception:
```
2020-03-20 18:12:14,524 - pypsrp.wsman - DEBUG - Initialising WSMan class with maximum envelope size of 153600 and operation timeout of 20
2020-03-20 18:12:14,524 - pypsrp.wsman - DEBUG - Initialising HTTP transport for endpoint: http://srv-exch01-dca:80/PowerShell, auth: USER, user: kerberos
2020-03-20 18:12:14,525 - pypsrp.wsman - DEBUG - Creating WSMan header (Action: http://schemas.microsoft.com/wbem/wsman/1/windows/shell/Send, Resource URI: http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd, Option Set: None, Selector Set: {'ShellId': '00000000-0000-0000-0000-000000000000'}
2020-03-20 18:12:14,525 - pypsrp.powershell - INFO - Initialising RunspacePool object for configuration Microsoft.Exchange
2020-03-20 18:12:14,526 - pypsrp.powershell - INFO - Openning a new Runspace Pool on remote host
2020-03-20 18:12:14,527 - pypsrp.messages - DEBUG - Packing PSRP message: <Obj RefId="0"><MS><Version N="protocolversion">2.3</Version><Version N="PSVersion">2.0</Version><Version N="SerializationVersion">1.1.0.1</Version></MS></Obj>
2020-03-20 18:12:14,528 - pypsrp.messages - DEBUG - Packing PSRP message: <Obj RefId="0"><MS><I32 N="MinRunspaces">1</I32><I32 N="MaxRunspaces">1</I32><Obj N="PSThreadOptions" RefId="1"><TN RefId="0"><T>System.Management.Automation.Runspaces.PSThreadOptions</T><T>System.Enum</T><T>System.ValueType</T><T>System.Object</T></TN><ToString>Default</ToString><I32>0</I32></Obj><Obj N="ApartmentState" RefId="2"><TN RefId="1"><T>System.Management.Automation.Runspaces.ApartmentState</T><T>System.Enum</T><T>System.ValueType</T><T>System.Object</T></TN><ToString>UNKNOWN</ToString><I32>2</I32></Obj><Obj N="HostInfo" RefId="3"><MS><B N="_isHostNull">true</B><B N="_isHostUINull">true</B><B N="_isHostRawUINull">true</B><B N="_useRunspaceHost">true</B></MS></Obj><Nil N="ApplicationArguments" /></MS></Obj>
2020-03-20 18:12:14,528 - pypsrp.wsman - DEBUG - Creating WSMan header (Action: http://schemas.xmlsoap.org/ws/2004/09/transfer/Create, Resource URI: http://schemas.microsoft.com/powershell/Microsoft.Exchange, Option Set: {'protocolversion': '2.3'}, Selector Set: None
2020-03-20 18:12:14,529 - pypsrp.wsman - DEBUG - Building requests session with auth kerberos
2020-03-20 18:12:14,531 - pypsrp.encryption - DEBUG - Initialising WinRMEncryption helper for protocol application/HTTP-SPNEGO-session-encrypted
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    with RunspacePool(wsman, configuration_name="Microsoft.Exchange") as pool:
  File "C:\Python\lib\site-packages\pypsrp\powershell.py", line 200, in __enter__
    self.open()
  File "C:\Python\lib\site-packages\pypsrp\powershell.py", line 508, in open
    self.shell.open(options, open_content)
  File "C:\Python\lib\site-packages\pypsrp\shell.py", line 204, in open
    option_set=options)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 259, in create
    option_set, selector_set, timeout)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 378, in invoke
    response = self.transport.send(xml)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 711, in send
    self._send_request(prep_request, hostname)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 739, in _send_request
    self.connection_timeout, self.read_timeout
  File "C:\Python\lib\site-packages\requests\sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "C:\Python\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "C:\Python\lib\site-packages\pypsrp\negotiate.py", line 85, in response_hook
    self._check_auth_supported(response, "Negotiate")
  File "C:\Python\lib\site-packages\pypsrp\negotiate.py", line 137, in _check_auth_supported
    raise AuthenticationError(error_msg)
pypsrp.exceptions.AuthenticationError: The server did not response with the authentication method of Negotiate - actual: 'Kerberos'
```

I set `auth="kerberos"` in the code above, but get that server `did not response with the authentication method of Negotiate`.
Hope this helps.

**Comment by jborean93** [comment]
Looks like pypsrp is expecting the `www-authenticate` header from the server to contain `Negotiate` but it just has `Kerberos`, will see if I can create a PR sometime today.

**Comment by NotSoWell** [comment]
Ok, so i just added adapter for .upper() method now, so i can pass list ["Negotiate", "Kerberos"] in auth_provider argument.

But, i got another problem. You don't mind if i continue this issue or i need to create another?
I just think that many people has problems with connection with Exchange server - this thread may help them.

**Comment by NotSoWell** [comment]
(If needed i will create another issue and delete this message)

So i got this stacktrace:
```
2020-03-23 19:32:53,607 - pypsrp.wsman - DEBUG - Initialising WSMan class with maximum envelope size of 153600 and operation timeout of 20
2020-03-23 19:32:53,607 - pypsrp.wsman - DEBUG - Initialising HTTP transport for endpoint: http://srv-exch01-dca:80/PowerShell, auth: USER, user: kerberos
2020-03-23 19:32:53,608 - pypsrp.wsman - DEBUG - Creating WSMan header (Action: http://schemas.microsoft.com/wbem/wsman/1/windows/shell/Send, Resource URI: http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd, Option Set: None, Selector Set: {'ShellId': '00000000-0000-0000-0000-000000000000'}
2020-03-23 19:32:53,609 - pypsrp.powershell - INFO - Initialising RunspacePool object for configuration Microsoft.Exchange
2020-03-23 19:32:53,609 - pypsrp.powershell - INFO - Openning a new Runspace Pool on remote host
2020-03-23 19:32:53,610 - pypsrp.messages - DEBUG - Packing PSRP message: <Obj RefId="0"><MS><Version N="protocolversion">2.3</Version><Version N="PSVersion">2.0</Version><Version N="SerializationVersion">1.1.0.1</Version></MS></Obj>
2020-03-23 19:32:53,611 - pypsrp.messages - DEBUG - Packing PSRP message: <Obj RefId="0"><MS><I32 N="MinRunspaces">1</I32><I32 N="MaxRunspaces">1</I32><Obj N="PSThreadOptions" RefId="1"><TN RefId="0"><T>System.Management.Automation.Runspaces.PSThreadOptions</T><T>System.Enum</T><T>System.ValueType</T><T>System.Object</T></TN><ToString>Default</ToString><I32>0</I32></Obj><Obj N="ApartmentState" RefId="2"><TN RefId="1"><T>System.Management.Automation.Runspaces.ApartmentState</T><T>System.Enum</T><T>System.ValueType</T><T>System.Object</T></TN><ToString>UNKNOWN</ToString><I32>2</I32></Obj><Obj N="HostInfo" RefId="3"><MS><B N="_isHostNull">true</B><B N="_isHostUINull">true</B><B N="_isHostRawUINull">true</B><B N="_useRunspaceHost">true</B></MS></Obj><Nil N="ApplicationArguments" /></MS></Obj>
2020-03-23 19:32:53,612 - pypsrp.wsman - DEBUG - Creating WSMan header (Action: http://schemas.xmlsoap.org/ws/2004/09/transfer/Create, Resource URI: http://schemas.microsoft.com/powershell/Microsoft.Exchange, Option Set: {'protocolversion': '2.3'}, Selector Set: None
2020-03-23 19:32:53,612 - pypsrp.wsman - DEBUG - Building requests session with auth kerberos
2020-03-23 19:32:53,615 - pypsrp.encryption - DEBUG - Initialising WinRMEncryption helper for protocol application/HTTP-SPNEGO-session-encrypted
2020-03-23 19:32:53,638 - pypsrp.spnego - DEBUG - SSPI is available and will be used as the auth backend
2020-03-23 19:32:53,685 - pypsrp.negotiate - DEBUG - Sending http request with new auth token
2020-03-23 19:32:53,693 - pypsrp.negotiate - DEBUG - Did not receive a http response with an auth response, stopping authentication process
2020-03-23 19:32:53,694 - pypsrp.wsman - DEBUG - Received message: 
2020-03-23 19:32:53,694 - pypsrp.wsman - ERROR - Failed to parse WSManFault message on WinRM error response, raising original WinRMTransportError
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 382, in invoke
    raise self._parse_wsman_fault(err.response_text)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 515, in _parse_wsman_fault
    xml = ET.fromstring(xml_text)
  File "C:\Python\lib\xml\etree\ElementTree.py", line 1315, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:/ДОБП/_персонал/Смирнов/testpy/test.py", line 15, in <module>
    with RunspacePool(wsman, configuration_name="Microsoft.Exchange") as pool:
  File "C:\Python\lib\site-packages\pypsrp\powershell.py", line 200, in __enter__
    self.open()
  File "C:\Python\lib\site-packages\pypsrp\powershell.py", line 508, in open
    self.shell.open(options, open_content)
  File "C:\Python\lib\site-packages\pypsrp\shell.py", line 204, in open
    option_set=options)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 259, in create
    option_set, selector_set, timeout)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 387, in invoke
    raise err
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 378, in invoke
    response = self.transport.send(xml)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 711, in send
    self._send_request(prep_request, hostname)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 765, in _send_request
    raise WinRMTransportError('http', code, response_text)
pypsrp.exceptions.WinRMTransportError: Bad HTTP response returned from the server. Code: 400, Content: ''

Process finished with exit code 1
```

Now i see that you also pass "Negotiate" in _set_auth_token() method, so if i change that to "Kerberos" i got this stacktrace:
```
2020-03-23 19:45:52,327 - pypsrp.wsman - DEBUG - Initialising WSMan class with maximum envelope size of 153600 and operation timeout of 20
2020-03-23 19:45:52,327 - pypsrp.wsman - DEBUG - Initialising HTTP transport for endpoint: http://srv-exch01-dca:80/PowerShell, auth: DIXY\cash, user: kerberos
2020-03-23 19:45:52,327 - pypsrp.wsman - DEBUG - Creating WSMan header (Action: http://schemas.microsoft.com/wbem/wsman/1/windows/shell/Send, Resource URI: http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd, Option Set: None, Selector Set: {'ShellId': '00000000-0000-0000-0000-000000000000'}
2020-03-23 19:45:52,328 - pypsrp.powershell - INFO - Initialising RunspacePool object for configuration Microsoft.Exchange
2020-03-23 19:45:52,329 - pypsrp.powershell - INFO - Openning a new Runspace Pool on remote host
2020-03-23 19:45:52,330 - pypsrp.messages - DEBUG - Packing PSRP message: <Obj RefId="0"><MS><Version N="protocolversion">2.3</Version><Version N="PSVersion">2.0</Version><Version N="SerializationVersion">1.1.0.1</Version></MS></Obj>
2020-03-23 19:45:52,331 - pypsrp.messages - DEBUG - Packing PSRP message: <Obj RefId="0"><MS><I32 N="MinRunspaces">1</I32><I32 N="MaxRunspaces">1</I32><Obj N="PSThreadOptions" RefId="1"><TN RefId="0"><T>System.Management.Automation.Runspaces.PSThreadOptions</T><T>System.Enum</T><T>System.ValueType</T><T>System.Object</T></TN><ToString>Default</ToString><I32>0</I32></Obj><Obj N="ApartmentState" RefId="2"><TN RefId="1"><T>System.Management.Automation.Runspaces.ApartmentState</T><T>System.Enum</T><T>System.ValueType</T><T>System.Object</T></TN><ToString>UNKNOWN</ToString><I32>2</I32></Obj><Obj N="HostInfo" RefId="3"><MS><B N="_isHostNull">true</B><B N="_isHostUINull">true</B><B N="_isHostRawUINull">true</B><B N="_useRunspaceHost">true</B></MS></Obj><Nil N="ApplicationArguments" /></MS></Obj>
2020-03-23 19:45:52,331 - pypsrp.wsman - DEBUG - Creating WSMan header (Action: http://schemas.xmlsoap.org/ws/2004/09/transfer/Create, Resource URI: http://schemas.microsoft.com/powershell/Microsoft.Exchange, Option Set: {'protocolversion': '2.3'}, Selector Set: None
2020-03-23 19:45:52,332 - pypsrp.wsman - DEBUG - Building requests session with auth kerberos
2020-03-23 19:45:52,334 - pypsrp.encryption - DEBUG - Initialising WinRMEncryption helper for protocol application/HTTP-SPNEGO-session-encrypted
2020-03-23 19:45:52,357 - pypsrp.spnego - DEBUG - SSPI is available and will be used as the auth backend
2020-03-23 19:45:52,404 - pypsrp.negotiate - DEBUG - Sending http request with new auth token
2020-03-23 19:45:52,419 - pypsrp.negotiate - DEBUG - Did not receive a http response with an auth response, stopping authentication process
2020-03-23 19:45:52,420 - pypsrp.wsman - DEBUG - Received message: 
2020-03-23 19:45:52,420 - pypsrp.wsman - DEBUG - Sending message: b'<s:Envelope xmlns:rsp="http://schemas.microsoft.com/wbem/wsman/1/windows/shell" xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsman="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:wsmv="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd"><s:Header><wsa:Action s:mustUnderstand="true">http://schemas.xmlsoap.org/ws/2004/09/transfer/Create</wsa:Action><wsmv:DataLocale s:mustUnderstand="false" xml:lang="en-US" /><wsman:Locale s:mustUnderstand="false" xml:lang="en-US" /><wsman:MaxEnvelopeSize s:mustUnderstand="true">153600</wsman:MaxEnvelopeSize><wsa:MessageID>uuid:637AE95A-0064-40C7-9F98-91DE41F3D769</wsa:MessageID><wsman:OperationTimeout>PT20S</wsman:OperationTimeout><wsa:ReplyTo><wsa:Address s:mustUnderstand="true">http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:Address></wsa:ReplyTo><wsman:ResourceURI s:mustUnderstand="true">http://schemas.microsoft.com/powershell/Microsoft.Exchange</wsman:ResourceURI><wsmv:SessionId s:mustUnderstand="false">uuid:2A15AA91-7A9E-4DAF-B423-C380E537DE43</wsmv:SessionId><wsa:To>http://srv-exch01-dca:80/PowerShell</wsa:To><wsman:OptionSet s:mustUnderstand="true"><wsman:Option MustComply="true" Name="protocolversion">2.3</wsman:Option></wsman:OptionSet></s:Header><s:Body><rsp:Shell ShellId="10155108-F8EF-4A8B-8C05-2E2C27485784"><rsp:InputStreams>stdin pr</rsp:InputStreams><rsp:OutputStreams>stdout</rsp:OutputStreams><creationXml xmlns="http://schemas.microsoft.com/powershell">AAAAAAAAAAEAAAAAAAAAAAMAAADHAgAAAAIAAQAIURUQ7/iLSowFLiwnSFeEAAAAAAAAAAAAAAAAAAAAADxPYmogUmVmSWQ9IjAiPjxNUz48VmVyc2lvbiBOPSJwcm90b2NvbHZlcnNpb24iPjIuMzwvVmVyc2lvbj48VmVyc2lvbiBOPSJQU1ZlcnNpb24iPjIuMDwvVmVyc2lvbj48VmVyc2lvbiBOPSJTZXJpYWxpemF0aW9uVmVyc2lvbiI+MS4xLjAuMTwvVmVyc2lvbj48L01TPjwvT2JqPgAAAAAAAAACAAAAAAAAAAADAAAC/QIAAAAEAAEACFEVEO/4i0qMBS4sJ0hXhAAAAAAAAAAAAAAAAAAAAAA8T2JqIFJlZklkPSIwIj48TVM+PEkzMiBOPSJNaW5SdW5zcGFjZXMiPjE8L0kzMj48STMyIE49Ik1heFJ1bnNwYWNlcyI+MTwvSTMyPjxPYmogTj0iUFNUaHJlYWRPcHRpb25zIiBSZWZJZD0iMSI+PFROIFJlZklkPSIwIj48VD5TeXN0ZW0uTWFuYWdlbWVudC5BdXRvbWF0aW9uLlJ1bnNwYWNlcy5QU1RocmVhZE9wdGlvbnM8L1Q+PFQ+U3lzdGVtLkVudW08L1Q+PFQ+U3lzdGVtLlZhbHVlVHlwZTwvVD48VD5TeXN0ZW0uT2JqZWN0PC9UPjwvVE4+PFRvU3RyaW5nPkRlZmF1bHQ8L1RvU3RyaW5nPjxJMzI+MDwvSTMyPjwvT2JqPjxPYmogTj0iQXBhcnRtZW50U3RhdGUiIFJlZklkPSIyIj48VE4gUmVmSWQ9IjEiPjxUPlN5c3RlbS5NYW5hZ2VtZW50LkF1dG9tYXRpb24uUnVuc3BhY2VzLkFwYXJ0bWVudFN0YXRlPC9UPjxUPlN5c3RlbS5FbnVtPC9UPjxUPlN5c3RlbS5WYWx1ZVR5cGU8L1Q+PFQ+U3lzdGVtLk9iamVjdDwvVD48L1ROPjxUb1N0cmluZz5VTktOT1dOPC9Ub1N0cmluZz48STMyPjI8L0kzMj48L09iaj48T2JqIE49Ikhvc3RJbmZvIiBSZWZJZD0iMyI+PE1TPjxCIE49Il9pc0hvc3ROdWxsIj50cnVlPC9CPjxCIE49Il9pc0hvc3RVSU51bGwiPnRydWU8L0I+PEIgTj0iX2lzSG9zdFJhd1VJTnVsbCI+dHJ1ZTwvQj48QiBOPSJfdXNlUnVuc3BhY2VIb3N0Ij50cnVlPC9CPjwvTVM+PC9PYmo+PE5pbCBOPSJBcHBsaWNhdGlvbkFyZ3VtZW50cyIgLz48L01TPjwvT2JqPg==</creationXml></rsp:Shell></s:Body></s:Envelope>'
2020-03-23 19:45:52,420 - pypsrp.encryption - DEBUG - Wrapping message for host: srv-exch01-dca
Traceback (most recent call last):
  File "W:/ДОБП/_персонал/Смирнов/testpy/test.py", line 15, in <module>
    with RunspacePool(wsman, configuration_name="Microsoft.Exchange") as pool:
  File "C:\Python\lib\site-packages\pypsrp\powershell.py", line 200, in __enter__
    self.open()
  File "C:\Python\lib\site-packages\pypsrp\powershell.py", line 508, in open
    self.shell.open(options, open_content)
  File "C:\Python\lib\site-packages\pypsrp\shell.py", line 204, in open
    option_set=options)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 259, in create
    option_set, selector_set, timeout)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 378, in invoke
    response = self.transport.send(xml)
  File "C:\Python\lib\site-packages\pypsrp\wsman.py", line 721, in send
    hostname)
  File "C:\Python\lib\site-packages\pypsrp\encryption.py", line 43, in wrap_message
    encrypted_msg = self._wrap_message(message, hostname)
  File "C:\Python\lib\site-packages\pypsrp\encryption.py", line 85, in _wrap_message
    wrapped_data = self._wrap(message, hostname)
  File "C:\Python\lib\site-packages\pypsrp\encryption.py", line 102, in _wrap_spnego
    header, wrapped_data = context.wrap(data)
  File "C:\Python\lib\site-packages\pypsrp\spnego.py", line 274, in wrap
    enc_data, header = self._context.encrypt(data)
  File "C:\Users\CASH\AppData\Roaming\Python\Python36\site-packages\win32\lib\sspi.py", line 43, in encrypt
    pkg_size_info=self.ctxt.QueryContextAttributes(sspicon.SECPKG_ATTR_SIZES)
pywintypes.error: (-2146893055, 'QueryContextAttributes', 'The handle specified is invalid')
```

Maybe this helps

**Comment by jborean93** [comment]
The latter seems to indicate that the SSPI context has been destroyed so we can no longer encrypt the data. Is this is local exchange host or one in Azure? Just wanting to try and test this against the proper endpoint.

**Comment by NotSoWell** [comment]
> The latter seems to indicate that the SSPI context has been destroyed so we can no longer encrypt the data. Is this is local exchange host or one in Azure? Just wanting to try and test this against the proper endpoint.

It is local

**Comment by NotSoWell** [comment]
I think we might actually contact in Discord - i can turn on screen presentation and start debugger. Please, contact me (Carius#5614) if you need additional information about the problem.

**Comment by jborean93** [comment]
@NotSoWell I haven't gotten around to actually setting up an Exchange host to test on but I can replicate the `Kerberos` header being sent instead of `Negotiate` by running `Set-Item -Path WSMan:\localhost\Service\Auth\Negotiate -Value $false` and connecting to a normal PowerShell endpoint.

From there I've made changes on the [auth-header](https://github.com/jborean93/pypsrp/tree/auth-header) branch that gets this working again so I'm curious whether it fixes the problem you have here. It does look like your SSPI failure is unrelated to that header problem so I'll still continue to look into it but thought it best to give you an update.

**Comment by jborean93** [comment]
Just an update on the progress, I’ve been able to get encryption working for the initial request but am coming across a weird issue with processing the result from an Exchange server. I’ve got some uncommitted changes that will be needed to progress further but will commit them once I’ve tidied up the changes

Unfortunately I still need to solve the problem with a response of random binary data before I can continue on. Hopefully https://social.msdn.microsoft.com/Forums/en-US/57709b1d-0578-4ee3-bbc8-975024ed2aee/powershell-remoting-on-exchange-encrypted-data?forum=os_windowsprotocols can shed some more light on this problem.

**Comment by XityZhang** [comment]
> 好的，所以我现在为.upper（）方法添加了适配器，因此我可以在auth_provider参数中传递列表[“ Negotiate”，“ Kerberos”]。
> 
> 但是，我有另一个问题。您不介意我继续这个问题还是需要创建另一个问题？
> 我只是认为很多人在与Exchange Server的连接方面遇到问题-此线程可能会对他们有所帮助。

hey, I met the same problem and can u tell me how to use upper() method to fix? thanks!

**Comment by XityZhang** [comment]
> Ok, so i just added adapter for .upper() method now, so i can pass list ["Negotiate", "Kerberos"] in auth_provider argument.
> 
> But, i got another problem. You don't mind if i continue this issue or i need to create another?
> I just think that many people has problems with connection with Exchange server - this thread may help them.

hey, I met the same problem and can u tell me how to use upper() method to fix? thanks!

**Comment by jborean93** [comment]
I was having another shot at this this morning and have figured out the final problem with the random binary data in the response. It turns out requests automatically adds the `Accept-Encoding: gzip, deflate` header to the HTTP request. Normally this does nothing because WinRM doesn't use that value for anything but because exchange endpoints are managed by IIS it's actually compressing the data that it's sending to pypsrp. The fix I've found so far is to set the header to `Accept-Encoding: identity` to avoid the compression from happening and I've added that change to the [auth-header](https://github.com/jborean93/pypsrp/tree/auth-header) branch but it's not really ready to merge into master just yet. I'll keep this issue open until those changes have been merged as I'm planning a big overhaul of the authentication process which is something that is touched in that branch.

Just for reflection purposes here are the following problems when it comes to connecting to an on prem Exchange session

* The `Authorization` header is always sent as `Negotiate <base64 token>` but Exchange only works on pure Kerberos so it must be `Kerberos <base64 token>`
* The encryption MIME data should have a content type of `application/HTTP-Kerberos-session-encryption` whereas it's currently using `application/HTTP-SPNEGO-session-encryption` for either NTLM or Kerberos auth. This is a similar problem to the point above
* The MIME boundary sent by IIS is actually `-- End Boundary` and not `--End Boundary` (no space after -). This does not match the spec for MIME data but something that needs to be handled
* Finally the header `Accept-Encoding: identity` needs to be set on the session so IIS won't encrypt the data that it responds with

**Comment by jborean93** [comment]
This fix has been implemented with https://github.com/jborean93/pypsrp/pull/78. That PR solves the problem when the HTTP service only returns `Kerberos` in it's headers, the message encryption requirements, as well as the issue with the `Accept-Encoding` header.
