### ISSUE TITLE
KeyError in serializer.py

### ISSUE THREAD

**Issue by gurrapp** [jborean93/pypsrp#71]
Same as #3. 
I'm getting the same error as in issue #3 

```Traceback (most recent call last):
  File "testpypsrp.py", line 23, in <module>
    ps.end_invoke()
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/powershell.py", line 1070, in end_invoke
    self.poll_invoke()
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/powershell.py", line 1245, in poll_invoke
    timeout=timeout)
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/powershell.py", line 637, in _receive
    return self._parse_responses(response, pipeline)
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/powershell.py", line 640, in _parse_responses
    messages = self._fragmenter.defragment(responses)
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/powershell.py", line 1454, in defragment
    for fragment in fragments]
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/powershell.py", line 1454, in <listcomp>
    for fragment in fragments]
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/messages.py", line 205, in unpack
    message = serializer.deserialize(message_data, message_meta)
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/serializer.py", line 356, in deserialize
    obj = self._deserialize_obj(element, metadata)
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/serializer.py", line 640, in _deserialize_obj
    deserialize_property("MS/", obj._extended_properties)
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/serializer.py", line 634, in deserialize_property
    val = self.deserialize(val, property_meta, clear=False)
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/serializer.py", line 658, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/serializer.py", line 358, in deserialize
    obj = self._deserialize_dynamic_obj(element, metadata)
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/serializer.py", line 658, in _deserialize_dynamic_obj
    value = self.deserialize(adapted_property, clear=False)
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/serializer.py", line 213, in deserialize
    return unpack_function(element)
  File "/Users/gurrap/src/lib/python3.7/site-packages/pypsrp/serializer.py", line 209, in <lambda>
    'Ref': lambda d: self.obj[d.attrib['RefId']],
KeyError: '5'
```

I tried doing the steps as described in the issue #3 but I'm not able to get a log file generated.
My code snippets looks something like:
```
cmd = """
    $excpassword = ConvertTo-SecureString 'XXXX' -AsPlainText -Force
    $credential = New-Object System.Management.Automation.PSCredential ('SVCAADSync002@XXXX', $excpassword)

    Connect-AzureAd -Credential $credential -TenantId "XXXX"
    Get-AzureAdGroupMember -ObjectId "XXXX" -All | Select-Object -Property DisplayName, UserPrincipalName, Mail, CompanyName | Format-List"""

conn = pypsrp.wsman.WSMan("host", ssl=False, auth="ntlm", username="gustpete0001",
                          password="***")


with pypsrp.powershell.RunspacePool(conn) as pool:
    ps = pypsrp.powershell.PowerShell(pool)

    ps.add_script(cmd)
    ps.begin_invoke(["string", 1])  # execute process in the background
    ps.end_invoke()

    for i in ps.streams.error:
        print(i)

    output = ps.output


for i in output:
    print(i)
```

**Comment by jborean93** [comment]
If you can setup the logs are per https://github.com/jborean93/pypsrp/issues/3#issuecomment-416427287 and share the log file that will go a long way for me trying to replicate the problem. If you are having troubles with getting the log file to appear make sure you have set `PYPSRP_LOG_CFG` to file path where you want the log to be generated.

**Comment by jborean93** [comment]
See https://github.com/jborean93/pypsrp/issues/70#issuecomment-662750889.

**Comment by gurrapp** [comment]
Awesomesauce!
