### ISSUE TITLE
AuthenticationException at win_copy module

### ISSUE THREAD

**Issue by RichMan-Yi** [jborean93/pypsrp#86]
It happens when I launch a large zip file(about 77MB)
from my ansible control node (Linux) to remote windows host
via a task using win_copy module

Here's my ansible host connection settings:

ansible_connection: 'psrp'
ansible_psrp_protocol: 'http'
ansible_psrp_auth: 'credssp'
ansible_psrp_credssp_minimum_version: 5

In this settings, other windows module work fine (like win_ping, win_file).
But when it come to win_copy, it will response the error message:
"""
AuthenticationException: Server did not response with a CredSSP token after step Step 5. Delegate Credentials - actual ''
"""

And I've tried some cases below:
- use a much smaller file(1kb), works fine
- ansible_psrp_auth change to 'ntlm', works fine too
- alter ansible_connection from 'psrp' to 'winrm', also works fine(list below is my settings)
  - ansible_connection: 'winrm'
  - ansible_winrm_port: 5985
  - ansible_winrm_transport: 'credssp'

And I've tried adding some timeout settings like
- ansible_psrp_connection_timeout: 300
- ansible_psrp_operation_timeout: 300
- ansible_psrp_read_timeout: 300
But it seems not helping

I choosed to use PSRP because I connect my remote windows host 
with a linux bastion host that will setup a proxy at hostvar: ansible_psrp_proxy.
But I'm stuck at this issue for a while, hope this post would help figure out what's the problem is.
Will be really gratful if noticed :)

**Comment by jborean93** [comment]
This looks to be a potential problem in Ansible with how it treats a copy operation. Can you run with `-vvv` and share the full output which includes the traceback.

**Comment by RichMan-Yi** [comment]
Here's the full callstack with -vvv below:
=====
TASK [execution-role-of-deploy : Copy Pack File] *******************************
task path: /home/opadmin/ansible_yi/execution-using-deploystate/roles/execution-role-of-deploy/tasks/deploy-of-windows.yml:67
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_copy.ps1
Pipelining is enabled.
<10.151.16.236> ESTABLISH PSRP CONNECTION FOR USER: opadmin ON PORT 5985 TO 10.151.16.236
PSRP: EXEC (via pipeline wrapper)
<10.151.16.236> PSRP: EXEC Set-StrictMode -Version Latest
$tmp_path = [System.Environment]::ExpandEnvironmentVariables('%TEMP%')
$tmp = New-Item -Type Directory -Path $tmp_path -Name 'ansible-tmp-1597040139.05-94960328835647'
Write-Output -InputObject $tmp.FullName
If (-not $?) { If (Get-Variable LASTEXITCODE -ErrorAction SilentlyContinue) { exit $LASTEXITCODE } Else { exit 1 } }
<10.151.16.236> PUT /tmp/deployment.zip TO C:\Users\opadmin\AppData\Local\Temp\ansible-tmp-1597040139.05-94960328835647\source
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/win_copy.py", line 501, in run
    task_vars, self._connection._shell.tmpdir, backup))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/win_copy.py", line 270, in _copy_single_file
    self._transfer_file(local_file, tmp_src)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 411, in _transfer_file
    self._connection.put_file(local_path, remote_path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/psrp.py", line 473, in put_file
    process.signal(SignalCode.CTRL_C)
  File "/usr/lib/python2.7/site-packages/pypsrp/shell.py", line 102, in __exit__
    self.close()
  File "/usr/lib/python2.7/site-packages/pypsrp/shell.py", line 110, in close
    self.wsman.delete(self.resource_uri, selector_set=self._selector_set)
  File "/usr/lib/python2.7/site-packages/pypsrp/wsman.py", line 271, in delete
    option_set, selector_set, timeout)
  File "/usr/lib/python2.7/site-packages/pypsrp/wsman.py", line 378, in invoke
    response = self.transport.send(xml)
  File "/usr/lib/python2.7/site-packages/pypsrp/wsman.py", line 735, in send
    return self._send_request(prep_request, hostname)
  File "/usr/lib/python2.7/site-packages/pypsrp/wsman.py", line 739, in _send_request
    self.connection_timeout, self.read_timeout
  File "/home/opadmin/.local/lib/python2.7/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/opadmin/.local/lib/python2.7/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests_credssp/credssp.py", line 448, in response_hook
    response = self.handle_401(response, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests_credssp/credssp.py", line 484, in handle_401
    step_name)
  File "/usr/lib/python2.7/site-packages/requests_credssp/credssp.py", line 517, in _get_credssp_token
    raise AuthenticationException(error_msg)
AuthenticationException: Server did not response with a CredSSP token after step Step 5. Delegate Credentials - actual ''

fatal: [master_aws_129936973651_us-east-1_1]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

**Comment by RichMan-Yi** [comment]
Btw I might choose to use "mount cifs" for larger files as a work-around.
It's also much faster then win_copy.
But if you need more information or test result of this issue, I'll be glad to help.

**Comment by jborean93** [comment]
That's a very weird error, it's stating that it failed when the CTRL+C signal was send which is way after the file was transferred to the remote host. I'm not sure why it's trying to renegotiate the authentication as that should already be done. What would be good to see is if there are any event log entries in the system or security event log on your Windows host. This might provide some more information as to why the CredSSP auth handler rejected that final token.

Using `mount cifs` will definitely be faster, WinRM is quite slow when it comes to file transfers as you need to send lots of small fragments with some overhead so it's not ideal.

**Comment by RichMan-Yi** [comment]
Here's the security event log of my remote Windows Host:

- Successful win_copy with WinRM settings
ansible_connection: 'winrm'
ansible_winrm_port: 5985
ansible_winrm_transport: 'credssp'
ansible_winrm_credssp_disable_tlsv1_2: false
![win_copy_winrm](https://user-images.githubusercontent.com/5449682/90207324-8af33f00-de18-11ea-8ad4-0c0b78ae2ef9.png)

- Failed win_copy with PSRP settings
ansible_connection: 'psrp'
ansible_psrp_protocol: 'http'
ansible_psrp_auth: 'credssp'
ansible_psrp_credssp_minimum_version: 5
![win_copy_psrp](https://user-images.githubusercontent.com/5449682/90207464-eb827c00-de18-11ea-93d9-399e5c0958d2.png)

I think the timing of the red line I drew would be just the time that server response the message below:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AuthenticationException: Server did not response with a CredSSP token after step Step 5. Delegate Credentials - actual ''
fatal: [win_test]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

And that log just shows "An account was logged off." as the picture below:
![log_off](https://user-images.githubusercontent.com/5449682/90207760-ad398c80-de19-11ea-8f84-4697b741de25.png)

Hope it would help.

**Comment by jborean93** [comment]
Thanks for the update, unfortunately there were no failures in there that would indicate why it was rejected at that stage. The winrm and psrp plugins are slightly different in how they copy the files. I've been meaning to update the psrp one at some point so maybe this will give me the impetus to do so.

**Comment by RichMan-Yi** [comment]
OKOK~Thank you for your attention :)

**Comment by jborean93** [comment]
Ansible has been updated to use a PSRP native copy mechanism and not the raw WinRM method that was there before. I'm not sure if it will fix your issue but in newer releases of Ansible, alongside newer versions of pypsrp, it no longer uses the older copy method.

I'm going to close this issue as the problem doesn't fully exist in this library but with some way that Ansible uses it. Since Ansible no longer uses it by default it should be ok now.

**Comment by RichMan-Yi** [comment]
The error msg become different (much longer)
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 393, in invoke
    raise self._parse_wsman_fault(err.response_text)
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 529, in _parse_wsman_fault
    xml = ET.fromstring(xml_text)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1321, in XML
    return parser.close()
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 663, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python3.8/site-packages/ansible_collections/ansible/windows/plugins/action/win_copy.py", line 505, in run
    result.update(self._copy_single_file(file_src, dest, basename, file_dest,
  File "/usr/lib/python3.8/site-packages/ansible_collections/ansible/windows/plugins/action/win_copy.py", line 270, in _copy_single_file
    self._transfer_file(local_file, tmp_src)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 475, in _transfer_file
    self._connection.put_file(local_path, remote_path)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/connection/psrp.py", line 463, in put_file
    rc, stdout, stderr, local_sha1 = self._put_file_new(in_path, out_path)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/connection/psrp.py", line 669, in _put_file_new
    rc, stdout, stderr = self._exec_psrp_script(copy_script, read_gen(), arguments=[out_path], force_stop=True)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/connection/psrp.py", line 872, in _exec_psrp_script
    ps.invoke(input=input_data)
  File "/usr/lib/python3.8/site-packages/pypsrp/powershell.py", line 1100, in invoke
    self.begin_invoke(input, add_to_history, apartment_state,
  File "/usr/lib/python3.8/site-packages/pypsrp/powershell.py", line 1067, in begin_invoke
    self.runspace_pool.shell.send('stdin', fragment,
  File "/usr/lib/python3.8/site-packages/pypsrp/shell.py", line 293, in send
    return self.wsman.send(self.resource_uri, send,
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 323, in send
    res = self.invoke(WSManAction.SEND, resource_uri, resource,
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 398, in invoke
    raise err
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 389, in invoke
    response = self.transport.send(xml)
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 761, in send
    return self._send_request(prep_request)
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 790, in _send_request
    raise WinRMTransportError('http', code, response_text)
pypsrp.exceptions.WinRMTransportError: Bad HTTP response returned from the server. Code: 413, Content: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 677, in _execute
    self._handler.cleanup()
  File "/usr/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 129, in cleanup
    self._remove_tmp_path(self._connection._shell.tmpdir)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 452, in _remove_tmp_path
    tmp_rm_res = self._low_level_execute_command(cmd, sudoable=False)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 1121, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/connection/psrp.py", line 450, in exec_command
    rc, stdout, stderr = self._exec_psrp_script(script, in_data)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/connection/psrp.py", line 872, in _exec_psrp_script
    ps.invoke(input=input_data)
  File "/usr/lib/python3.8/site-packages/pypsrp/powershell.py", line 1100, in invoke
    self.begin_invoke(input, add_to_history, apartment_state,
  File "/usr/lib/python3.8/site-packages/pypsrp/powershell.py", line 1039, in begin_invoke
    self._invoke(create_pipeline)
  File "/usr/lib/python3.8/site-packages/pypsrp/powershell.py", line 1293, in _invoke
    resp = self.runspace_pool.shell.command('', arguments=[first_frag],
  File "/usr/lib/python3.8/site-packages/pypsrp/shell.py", line 142, in command
    return self.wsman.command(self.resource_uri, cmd, option_set=options,
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 257, in command
    res = self.invoke(WSManAction.COMMAND, resource_uri, resource,
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 389, in invoke
    response = self.transport.send(xml)
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 761, in send
    return self._send_request(prep_request)
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 764, in _send_request
    response = self.session.send(request, timeout=(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests_credssp/credssp.py", line 444, in response_hook
    response = self.handle_401(response, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests_credssp/credssp.py", line 478, in handle_401
    in_token = self._get_credssp_token(response, credssp_regex, step_name)
  File "/usr/lib/python3.8/site-packages/requests_credssp/credssp.py", line 509, in _get_credssp_token
    raise AuthenticationException(error_msg)
requests_credssp.exceptions.AuthenticationException: Server did not response with a CredSSP token after step Step 5. Delegate Credentials - actual ''
fatal: [win_test]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```
