### ISSUE TITLE
Raise Exception when copying directory recursively

### ISSUE THREAD

**Issue by RichMan-Yi** [jborean93/pypsrp#93]
My Ansible task is quite simple as below
```
- name: Copy Dir
  win_command: 'XCOPY C:\\\\Dir1 C:\\\\Dir2 /E /I'
```
'Dir1' folder is about 10 mb large with several sub-folders and files
The Ansible task always take so long (about 2 minutes) and raise an exception eventually.
I'll put the callstack of exception below
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 663, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 969, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 1121, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/connection/psrp.py", line 450, in exec_command
    rc, stdout, stderr = self._exec_psrp_script(script, in_data)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/connection/psrp.py", line 872, in _exec_psrp_script
    ps.invoke(input=input_data)
  File "/usr/lib/python3.8/site-packages/pypsrp/powershell.py", line 1102, in invoke
    return self.end_invoke()
  File "/usr/lib/python3.8/site-packages/pypsrp/powershell.py", line 1078, in end_invoke
    self.poll_invoke()
  File "/usr/lib/python3.8/site-packages/pypsrp/powershell.py", line 1252, in poll_invoke
    responses = self.runspace_pool._receive(self.id,
  File "/usr/lib/python3.8/site-packages/pypsrp/powershell.py", line 640, in _receive
    response = self.shell.receive("stdout", command_id=command_id,
  File "/usr/lib/python3.8/site-packages/pypsrp/shell.py", line 238, in receive
    response = self.wsman.receive(self.resource_uri, receive,
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 311, in receive
    res = self.invoke(WSManAction.RECEIVE, resource_uri, resource,
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 389, in invoke
    response = self.transport.send(xml)
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 761, in send
    return self._send_request(prep_request)
  File "/usr/lib/python3.8/site-packages/pypsrp/wsman.py", line 771, in _send_request
    response_content = self.encryption.unwrap_message(response.content, to_unicode(boundary))
  File "/usr/lib/python3.8/site-packages/pypsrp/encryption.py", line 63, in unwrap_message
    expected_length = int(header.split(b"Length=")[1])
IndexError: list index out of range
```
Another weird thing is that there will be the same exception when I use win_robocopy:
```
- name: Copy Dir
  win_robocopy:
    src: 'C:\\\\Dir1'
    dest: 'C:\\\\Dir2'
    recurse: yes
    purge: yes
```
My develop env is
- Docker Desktop (HyperV backend)
- [container image info](https://hub.docker.com/layers/jfiop/ansible/2.10.2-py3/images/sha256-63f0f756ee711ea194bfb6a7f9db85ecdb32b4ee9c2ff31346b844f0f0981a9a?context=explore)

I already start trying some work-around
But still hope this post may help fix this issue :)

**Comment by jborean93** [comment]
That's very unusual as the copy is all happening on the remote end and the error that is happening is based on the WSMan encryption failure indicating some transport error. There shouldn't be anything that's really stressing the actual WSMan connection unless there's a massive amount of output being generated.

Can you see if:

* You can run this manually through the native PowerShell client (`Invoke-Command -ComputerName myhost -ScriptBlock { xcopy ... }`
* Try a different authentication protocol, use CredSSP instead of NTLM and vice versa
* See if you still have issues when running on HTTPS as message encryption isn't used there

**Comment by RichMan-Yi** [comment]
It seems that using NTLM could solve every "unwrap_message exception" in many different windows command. I would give up using CredSSP.

Thanks for your suggestion~!
